### ISSUE TITLE
Frontend-feat-gameview-layout

### ISSUE THREAD

**Issue by jeppeerixon** [JoeldelPilar/GridWars#12]
- [x] Make components
- [x] design simple layout

**Comment by Redicholas** [comment]
<img width="1258" alt="Screenshot 2023-04-21 at 13 08 22" src="https://user-images.githubusercontent.com/95872411/233621581-c86b3005-13ed-46ce-9437-fcd5bdce5216.png">

Enkel layout med mycket utrymme för mer styling
