### ISSUE TITLE
Frontend-feat-userStore

### ISSUE THREAD

**Issue by JoeldelPilar** [JoeldelPilar/GridWars#2]
tom array för att spara spelare
funktion för att pusha spelare in i arrayen

**Comment by jeppeerixon** [comment]
kanske behövs en store för val av färg också?

**Comment by JoeldelPilar** [comment]
Vi kan återanvända userStore för det tror jag. I komponenten för färg kan vi importera userStore och beroende på vad användaren väljer så sätter vi det som värdet på en egenskap för användaren.
users [ { userName: "Kalle", id: 1,  color: "#123456"}, fler users ]
