### ISSUE TITLE
Frontend-feat-topbar

### ISSUE THREAD

**Issue by JoeldelPilar** [JoeldelPilar/GridWars#7]
- [x] player presentation
- [ ] timer
- [ ] logo?

**Comment by jeppeerixon** [comment]
single player presentation done:
https://github.com/JoeldelPilar/GridWars/tree/frontend-feat-playerinfo-component

**Comment by jeppeerixon** [comment]
Bug: Hämta user från userStore vid reload för att förhindra crash
